/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RuRouteImport } from './routes/ru'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as EtRouteImport } from './routes/et'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBookingEmailRouteImport } from './routes/api/public/booking-email'

const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EtRoute = EtRouteImport.update({
  id: '/et',
  path: '/et',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingEmailRoute = ApiPublicBookingEmailRouteImport.update({
  id: '/api/public/booking-email',
  path: '/api/public/booking-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/et': typeof EtRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ru': typeof RuRoute
  '/api/public/booking-email': typeof ApiPublicBookingEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/et': typeof EtRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ru': typeof RuRoute
  '/api/public/booking-email': typeof ApiPublicBookingEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/et': typeof EtRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ru': typeof RuRoute
  '/api/public/booking-email': typeof ApiPublicBookingEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/et'
    | '/reset-password'
    | '/ru'
    | '/api/public/booking-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/et'
    | '/reset-password'
    | '/ru'
    | '/api/public/booking-email'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/et'
    | '/reset-password'
    | '/ru'
    | '/api/public/booking-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EtRoute: typeof EtRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RuRoute: typeof RuRoute
  ApiPublicBookingEmailRoute: typeof ApiPublicBookingEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/et': {
      id: '/et'
      path: '/et'
      fullPath: '/et'
      preLoaderRoute: typeof EtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-email': {
      id: '/api/public/booking-email'
      path: '/api/public/booking-email'
      fullPath: '/api/public/booking-email'
      preLoaderRoute: typeof ApiPublicBookingEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EtRoute: EtRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RuRoute: RuRoute,
  ApiPublicBookingEmailRoute: ApiPublicBookingEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
